---
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}

options(knitr.duplicate.label = 'allow')
options(tinytex.verbose = TRUE)

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE,
                      cache = FALSE,
                      cache.comments = FALSE,
                      include = TRUE,
                      autodep = TRUE,
                      eval = TRUE)

library(readxl)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)
library(scales)

dta2 <- readxl::read_xlsx("//deqhq1/WQ-Share/Harmful Algal Blooms Coordination Team/HAB_Shiny_app/data/HAB_resolvablelakes_2021.xlsx",
                          sheet = "HAB_resolvable_lake_data")

dta3 <- readxl::read_xlsx("//deqhq1/WQ-Share/Harmful Algal Blooms Coordination Team/HAB_Shiny_app/data/Resolvable_Lakes.xlsx",
                          sheet = "cyan_resolvable_lakes")

GNISNameID <- unique(sort(dta3$wi_DWSA))

plot.dta <- dta2 %>% 
  dplyr::rename(Mean = MEAN_cellsml,
                Maximum = MAX_cellsml,
                Minimum = MIN_cellsml) %>% 
  tidyr::gather(`Summary Statistics`, `Cyanobacteria (cells/mL)`, -GNISIDNAME,-COUNT,-AREA,-PercentArea_Value,-RANGE_cellsml,-STD_cellsml,-Day,-Year,-Date) %>% 
  tidyr::separate(GNISIDNAME,c("GNISNAME","GNISID"), sep="_") %>% 
  dplyr::mutate(GNISIDNAME = paste0(GNISNAME,"_",GNISID)) %>% 
  dplyr::mutate(Date = lubridate::ymd(Date)) %>% 
  dplyr::arrange(desc(Date)) %>% 
  dplyr::mutate(wi_DWSA = ifelse(GNISIDNAME %in% GNISNameID, "Yes", "No")) %>% 
  dplyr::filter(!GNISIDNAME == "Goose Lake_01520146") # located in the WA state

# cyano.max <- max(plot.dta$log_cyano)

gnisidname <- unique(sort(plot.dta$GNISIDNAME))

```
---
title: "`r paste0("CyAN Update (", min(dta2$Date)," - ", max(dta2$Date), ")")`"
---

```{r ggplot, fig.width=10, fig.height=5, echo=FALSE}

# test: i <- "Odell Lake_01147159"

for(i in gnisidname) {
  
    plot <- ggplot(subset(plot.dta, plot.dta$GNISIDNAME == i),
                 aes(x=as.Date(Date), y=`Cyanobacteria (cells/mL)`,
                     group=`Summary Statistics`,
                     color=`Summary Statistics`)) +
    geom_line(size=1.5) +
    geom_point(color="brown", alpha=0.3, size=1.5) +
    xlab("Date") +
    scale_x_date(date_labels = "%b-%d",
                 date_breaks = "week") +
    ylab("Cyanobacteria (cells/mL)") +
    scale_y_continuous(trans = log10_trans(),
                       breaks = trans_breaks("log10", function(x) 10^x),
                       labels = trans_format("log10", math_format(10^.x))) +
    ggtitle(i) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 10),
          axis.text.y = element_text(size = 10),
          axis.title.x = element_text(size = 12),
          axis.title.y = element_text(size = 12),
          plot.title = element_text(size=15))

  print(plot)
  
}

```