# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2016_Clip.py
# Created on: 2022-06-10 10:53:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
v2016_Tif = "\\\\deqhq1\\WQ-Share\\Harmful Algal Blooms Coordination Team\\HAB_Shiny_app\\data\\2016\\2016_Tif"
CyAN_Waterbodies = "CyAN_Waterbodies"
ClippedTiff = "\\\\deqhq1\\WQ-Share\\Harmful Algal Blooms Coordination Team\\HAB_Shiny_app\\data\\2016\\ClippedTiff"

# Process: Clip
arcpy.Clip_management(v2016_Tif, "359913.173905536 6505.3445386506 2245932.37791676 1528435.59763035", ClippedTiff, CyAN_Waterbodies, "", "NONE", "NO_MAINTAIN_EXTENT")

